all:
	cd ./httpCallBackServer && go build
	cd ./register_device && go build
	cd ./subscriptions && go build

clean:
	cd ./httpCallBackServer && rm -rf ./httpCallBackServer
	cd ./register_device &&  rm -rf ./register_device
	cd ./subscriptions && rm -rf ./subscriptions

